---
- hosts: localhost
  gather_facts: false
  vars:
    input: "2016-08-14 20:00:12"
    date: "{{ input | to_datetime('YYMMDDHHMM') }}"
  tasks:
    - debug:
        msg: "{{date}}"
    - fail:
    - ansible.controller.job_template:
        name: jt_from_playbook2
        validate_certs: false
        inventory: 5
        project: 21
        playbook: test.yml
      register: jt_res

    - debug:
        var: jt_res.id

    - ansible.controller.schedule:
        name: test_sc2
        unified_job_template: jt_from_playbook2
#        rrule: "{{ query(awx.awx.schedule_rruleset, '2024-04-30 10:30:00', rules=rrule, timezone='UTC') }}"
        rrule: "DTSTART:{{ date }}T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"
        validate_certs: false
