---
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        var: hoge
    - ansible.controller.job_template:
        name: jt_from_playbook2
        validate_certs: false
        inventory: 5
        project: 21
        playbook: test.yml
      register: jt_res

    - debug:
        var: jt_res.id

    - ansible.controller.schedule:
        name: test_sc2
        unified_job_template: jt_from_playbook2
#        rrule: "{{ query(awx.awx.schedule_rruleset, '2024-04-30 10:30:00', rules=rrule, timezone='UTC') }}"

        validate_certs: false
